src/Products/Entity/Order.php
<?php

declare(strict_types=1);

namespace App\Products\Entity;

use App\Users\DTO\OrderUpdateDTO;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'manga_orders')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private readonly DateTimeImmutable $createdAt;

    #[ORM\Column(type: 'string', length: 180)]
    private string $status = '1';

    /** @var Collection<int, OrderProduct> */
    #[ORM\OneToMany(mappedBy: 'order', targetEntity: OrderProduct::class, orphanRemoval: true)]
    private Collection $elements;

    public function __construct(
        #[ORM\Column(type: 'string', length: 180)]
        private string  $userName,
        #[ORM\Column(type: 'string', length: 180)]
        private string  $userPhone,
        #[ORM\Column(type: 'text', nullable: true)]
        private ?string $userComment,
        #[ORM\Column(type: 'integer', nullable: true)]
                        // TODO To relation maybe
        private readonly ?int $userId,
    )
    {
        $this->createdAt = new DateTimeImmutable();
        $this->elements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getStatusText(): string
    {
        return match ($this->status) {
            '1' => 'Новый заказ',
            '2' => 'В обработке',
            '3' => 'Доставляется',
            '4' => 'Закрыт',
            default => "Неизвестный статус: $this->status",
        };
    }

    public function getUserName(): string
    {
        return $this->userName;
    }

    public function getUserPhone(): string
    {
        return $this->userPhone;
    }

    public function getUserComment(): ?string
    {
        return $this->userComment;
    }

    public function getUserId(): ?int
    {
        return $this->userId;
    }

    public function updateInformation(OrderUpdateDTO $dto): void
    {
        $this->userName = $dto->userName;
        $this->userPhone = $dto->userPhone;
        $this->userComment = $dto->userComment;
        $this->status = $dto->status;
    }

    public function addElement(OrderProduct $orderProduct): void
    {
        $this->elements->add($orderProduct);
    }

    public function getElements(): Collection
    {
        return $this->elements;
    }
}

src/Users/Entity/User.php
<?php

namespace App\Users\Entity;

use App\Shared\Security\AuthUserInterface;
use App\Users\DTO\UserEditDTO;
use App\Users\Service\UserPasswordHasherInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity]
#[ORM\Table(name: 'manga_users')]
class User implements AuthUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    public function __construct(
        #[ORM\Column(length: 180)]
        private string          $name,
        #[ORM\Column(length: 180, unique: true)]
        private readonly string $email,
    )
    {
    }

    public function getId(): int
    {
        return $this->id ?? 0;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password, UserPasswordHasherInterface $passwordHasher): self
    {
        $this->password = $passwordHasher->hash($this, $password);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function updateInformation(UserEditDTO $dto): void
    {
        $this->name = $dto->newName;
    }
}

src/Admin/Controller/AdminOrderController.php
<?php

namespace App\Admin\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdminOrderController extends AbstractController
{
    #[Route('/admin/order', name: 'app_admin_order_index')]
    public function index(): Response
    {
        return $this->render('admin_order/index.html.twig');
    }

    #[Route('/admin/order/update/{id}')]
    public function update(int $id): Response
    {
        return $this->render('admin_order/update.html.twig');
    }

    #[Route('/admin/order/delete/{id}')]
    public function delete(int $id): Response
    {
        return $this->render('admin_order/delete.html.twig');
    }

    #[Route('/admin/order/view/{id}')]
    public function view(int $id): Response
    {
        return $this->render('admin_order/view.html.twig');
    }
}

src/Users/Controller/AdminController.php
<?php

declare(strict_types=1);

namespace App\Users\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/users')]
class AdminController extends AbstractController
{
    public function __construct()
    {
    }

    #[Route('/admin', name: 'app_admin_index')]
    public function index(): Response
    {
        return $this->render('users/admin/index.html.twig');
    }
}

src/Users/Controller/AdminOrderController.php
<?php

namespace App\Users\Controller;

use App\Products\Entity\Order;
use App\Products\Repository\OrderRepository;
use App\Products\Repository\ProductRepository;
use App\Shared\Service\SerializerServiceInterface;
use App\Users\DTO\OrderUpdateDTO;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/users')]
class AdminOrderController extends AbstractController
{
    public function __construct(
        private readonly OrderRepository            $orderRepository,
        private readonly ProductRepository          $productRepository,
        private readonly SerializerServiceInterface $serializerService,
        private readonly EntityManagerInterface     $entityManager,
    )
    {
    }

    #[Route('/admin/order', name: 'app_admin_order_index')]
    public function index(): Response
    {
        return $this->render('users/admin_order/index.html.twig', [
            'ordersList' => $this->orderRepository->findAll()
        ]);
    }

    #[Route('/admin/order/update/{id}', name: 'app_admin_order_update')]
    public function update(int $id, Request $request): Response
    {
        /** @var Order $order */
        $order = $this->orderRepository->find($id);

        if ($request->getContent()) {
            /** @var OrderUpdateDTO $dto */
            $dto = $this->serializerService->denormalize($request->request->all(), OrderUpdateDTO::class);
            $order->updateInformation($dto);
            $this->entityManager->flush();
            return $this->redirectToRoute('app_admin_order_index');
        }

        return $this->render('users/admin_order/update.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/admin/order/delete/{id}', name: 'app_admin_order_delete')]
    public function delete(int $id, Request $request): Response
    {
        /** @var Order $order */
        $order = $this->orderRepository->find($id);
        if ($request->request->get('accept')) {
            $this->entityManager->remove($order);
            $this->entityManager->flush();
            return $this->redirectToRoute('app_admin_order_index');
        }
        return $this->render('users/admin_order/delete.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/admin/order/view/{id}', name: 'app_admin_order_view')]
    public function view(int $id): Response
    {
        $order = $this->orderRepository->find($id);
        return $this->render('users/admin_order/view.html.twig', [
            'order' => $order,
            'orderProducts' => $order->getElements()
        ]);
    }

}

src/Users/Controller/AdminProductController.php
<?php

namespace App\Users\Controller;

use App\Products\Entity\Product;
use App\Products\Repository\ProductRepository;
use App\Shared\Service\SerializerServiceInterface;
use App\Users\DTO\ProductCreateDTO;
use App\Users\DTO\ProductUpdateDTO;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/users')]
class AdminProductController extends AbstractController
{
    public function __construct(
        private readonly ProductRepository          $productRepository,
        private readonly SerializerServiceInterface $serializerService,
        private readonly EntityManagerInterface     $entityManager,
        private readonly SluggerInterface           $slugger
    )
    {
    }

    #[Route('/admin/product', name: 'app_admin_product_index')]
    public function index(): Response
    {
        return $this->render('users/admin_product/index.html.twig', [
            'products' => $this->productRepository->findAll()
        ]);
    }

    #[Route('/admin/product/create', name: 'app_admin_product_create')]
    public function create(Request $request): Response
    {
        if ($request->request->get('submit')) {
            /** @var ProductUpdateDTO $dto */
            $dto = $this->serializerService->denormalize($request->request->all(), ProductCreateDTO::class);

            // Can be moved to factory:
            $product = new Product(
                name: $dto->name,
                code: (int)$dto->code,
                price: (float)$dto->price,
                description: $dto->description,
            );

            $imageFile = $request->files->get('image');
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $this->slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('product_images_directory_full_path'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw $e;
                }

                $product->setImage(
                    $this->getParameter('product_images_directory_path') . $newFilename
                );
            }

            $this->entityManager->persist($product);

            $this->entityManager->flush();

            return $this->redirectToRoute('app_admin_product_index');
        }

        $errors = [];
        return $this->render('users/admin_product/create.html.twig', [
            'errors' => $errors
        ]);
    }

    #[Route('/admin/product/update/{id}', name: 'app_admin_product_update')]
    public function update(int $id, Request $request): Response
    {
        /** @var Product $product */
        $product = $this->productRepository->find($id);

        if ($request->request->get('submit')) {
            /** @var ProductUpdateDTO $dto */
            $dto = $this->serializerService->denormalize($request->request->all(), ProductUpdateDTO::class);
            $product->updateInformation($dto);

            $imageFile = $request->files->get('image');
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $this->slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('product_images_directory_full_path'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw $e;
                }

                $product->setImage(
                    $this->getParameter('product_images_directory_path') . $newFilename
                );
            }
            $this->entityManager->flush();
            return $this->redirectToRoute('app_admin_product_index');
        }

        return $this->render('users/admin_product/update.html.twig', [
            'product' => $product
        ]);
    }

    #[Route('/admin/product/delete/{id}', name: 'app_admin_product_delete')]
    public function delete(int $id, Request $request): Response
    {
        /** @var Product $product */
        $product = $this->productRepository->find($id);
        if ($request->request->get('accept')) {
            $this->entityManager->remove($product);
            $this->entityManager->flush();
            return $this->redirectToRoute('app_admin_product_index');
        }

        return $this->render('users/admin_product/delete.html.twig', [
            'product' => $product
        ]);
    }
}

src/Users/Controller/MeController.php
<?php

declare(strict_types=1);

namespace App\Users\Controller;

use App\Shared\Security\UserFetcherInterface;
use App\Shared\Service\SerializerServiceInterface;
use App\Users\DTO\UserEditDTO;
use App\Users\Entity\User;
use App\Users\Repository\UserRepository;
use App\Users\Service\UserPasswordHasherInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[Route('/users')]
class MeController extends AbstractController
{
    public function __construct(
        private readonly UserRepository             $userRepository,
        private readonly UserFetcherInterface       $userFetcher,
        private readonly SerializerServiceInterface $serializerService,
        private readonly ValidatorInterface         $validator
    )
    {
    }

    #[Route('/me', name: 'app_me')]
    public function index(): Response
    {
        return $this->render('users/me/index.html.twig', [
            'user' => $this->userRepository->find(
                $this->userFetcher->getAuthUser()->getId()
            ),
        ]);
    }

    #[Route('/me/edit', name: 'app_me_edit', methods: ['GET', 'POST'])]
    public function edit(
        Request                     $request,
        UserPasswordHasherInterface $passwordHasher,
        EntityManagerInterface      $entityManager
    ): Response
    {
        $isSuccess = false;
        /** @var User $user */
        $user = $this->userRepository->find(
            $this->userFetcher->getAuthUser()->getId()
        );
        $errors = [];

        if ($request->getContent()){
            /** @var UserEditDTO $dto */
            $dto = $this->serializerService->denormalize($request->request->all(), UserEditDTO::class);

            $validationErrors = $this->validator->validate($dto);
            if ($validationErrors->count() > 0) {
                foreach ($validationErrors as $error) {
                    $errors[] = $error->getPropertyPath() . ' ' . $error->getMessage();
                }
            } else {
                // Update user
                $user->updateInformation($dto);
                if (!empty($dto->newPassword)) {
                    $user->setPassword($dto->newPassword, $passwordHasher);
                }
                $entityManager->flush();
                $isSuccess = true;
            }
        }

        return $this->render('users/me/edit.html.twig', [
            'errors' => $errors,
            'user' => $user,
            'isSuccess' => $isSuccess
        ]);
    }
}

templates/users/admin_order/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section>
        <div class="container mt-10 mb-10">
            <div class="text-center">
                <button class="bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mt-5">
                    <a href="{{ path('app_admin_index') }}">Админ панель</a>
                </button>
                <br>
                <button class="font-sans bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mt-5">
                    <a href="{{ path('app_admin_order_index') }}"> &#8592; Назад</a>
                </button>
                <h4 class="text-xl font-sans">Удалить заказ #{{ order.id }}</h4>
                <p class="text-xl font-sans">Вы действительно хотите удалить этот заказ?</p>
                <form method="post">
                    <input type="hidden" name="accept" value="1"/>
                    <input type="submit"
                           class="font-sans bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mt-5"
                           name="submit" value="Удалить"/>

                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/admin_order/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section>
        <div class="container mt-10 mb-10 ">
            <div class="text-center">
                <button class="bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mb-5">
                    <a href="{{ path('app_admin_index') }}"> &#8592; Назад</a>
                </button>
                <h4 class="mt-3 mb-2 text-2xl">Список заказов</h4>
                <div class="flex justify-center text-xl">
                    <table class="border-2 border-black table-bordered table-striped table ">
                        <tr class="border-2 border-black">
                            <th class="border-2 border-black px-4 py-2">ID заказа</th>
                            <th class="border-2 border-black px-4 py-2">Имя покупателя</th>
                            <th class="border-2 border-black px-4 py-2">Телефон покупателя</th>
                            <th class="border-2 border-black px-4 py-2">Дата оформления</th>
                            <th class="border-2 border-black px-4 py-2">Статус</th>
                            <th></th>
                        </tr>
                        {% for order in ordersList %}
                            <tr>
                                <td>
                                    <a href="{{ path('app_admin_order_view', {'id': order.id }) }}">
                                        {{ order.id }}
                                    </a>
                                </td>
                                <td>{{ order.username }}</td>
                                <td>{{ order.userPhone }}</td>
                                <td>{{ order.createdAt.format('d/m/Y - H:i') }}</td>
                                <td>{{ order.statusText }}</td>
                                <td>
                                    <a href="{{ path('app_admin_order_view', {'id': order.id }) }}" title="Смотреть">
                                        <svg class="h-8 w-8 text-black" fill="none" viewBox="0 0 24 24"
                                             stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                  d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                  d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                                        </svg>
                                        <i class=""></i>
                                    </a>
                                </td>
                                <td><a href="{{ path('app_admin_order_update', {'id': order.id }) }}" title="Редактировать">
                                        <svg class="h-8 w-8 text-black" width="24" height="24" viewBox="0 0 24 24"
                                             xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
                                             stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
                                            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
                                        </svg>
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ path('app_admin_order_delete', {'id': order.id }) }}" title="Удалить">
                                        <svg class="h-8 w-8 text-black" viewBox="0 0 24 24" fill="none"
                                             stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round">
                                            <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
                                            <line x1="9" y1="9" x2="15" y2="15"/>
                                            <line x1="15" y1="9" x2="9" y2="15"/>
                                        </svg>
                                        <i class="fa fa-times"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/admin_order/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="flex justify-center mt-10 mb-10">
        <div class="flex flex-col rounded-lg bg-zinc-200 shadow-lg">
            <div class="p-6 flex flex-col justify-start">
                <div class="text-center">
                    <button class="font-sans bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded  mt-5">
                        <a href="{{ path('app_admin_index') }}">Админ панель</a>
                    </button>
                    <br>
                    <button class="bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mt-5">
                        <a href="{{ path('app_admin_order_index') }}"> &#8592; Назад</a>
                    </button>
                    <h4 class="text-xl font-sans mb-2">Редактировать заказ #{{ order.id }}</h4>
                    <div class="col-lg-4 font-sans">
                        <div class="login-form">
                            <form action="{{ path('app_admin_order_update', { 'id': order.id }) }}" method="post">

                                <p class="mb-2 mt-2 font-sans text-xl">Клиент</p>
                                <input type="text" name="userName"
                                       class="border-2 border-black rounded py-1 px-2" placeholder=""
                                       value="{{ order.username }}">

                                <p class="mb-2 mt-2 font-sans text-xl">Телефон клиента</p>
                                <input type="text" name="userPhone"
                                       class="border-2 border-black rounded py-1 px-2" placeholder=""
                                       value="{{ order.userPhone }}">

                                <p class="mb-2 mt-2 font-sans text-xl">Комментарий клиента</p>
                                <input type="text" name="userComment"
                                       class="border-2 border-black rounded py-1 px-2" placeholder=""
                                       value="{{ order.userComment }}">

                                <p class="mb-2 mt-2 font-sans text-xl">Статус</p>
                                <select name="status" class="border-2 border-black rounded py-1 px-2">
                                    <option value="1"
                                            {% if order.status is same as '1' %} selected="selected"{% endif %}
                                    >Новый заказ
                                    </option>
                                    <option value="2"
                                            {% if order.status is same as '2' %} selected="selected"{% endif %}
                                    >В обработке
                                    </option>
                                    <option value="3"
                                            {% if order.status is same as '3' %} selected="selected"{% endif %}
                                    >Доставляется
                                    </option>
                                    <option value="4"
                                            {% if order.status is same as '4' %} selected="selected"{% endif %}
                                    >Закрыт
                                    </option>
                                </select>
                                <br>
                                <br>
                                <input type="submit" name="submit"
                                       class="bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mb-5"
                                       value="Сохранить">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/admin_order/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="flex justify-center mt-10 mb-10">
        <div class="flex flex-col rounded-lg bg-zinc-200 shadow-lg">
            <div class="p-6 flex flex-col justify-start">
                <div class="text-center">
                    <button class="bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mt-5">
                        <a href="{{ path('app_admin_index') }}">Админ панель</a>
                    </button>
                    <br>
                    <button class="font-sans bg-zinc-300 text-xl hover:bg-zinc-400 text-black py-2 px-4 rounded mt-5">
                        <a href="{{ path('app_admin_order_index') }}"> &#8592; Назад</a>
                    </button>
                    <h4 class="text-xl font-sans mb-2">Информация о заказе #{{ order.id }}</h4>
                    <div class="flex justify-center text-xl font-sans">
                        <table class="border-2 border-black table-bordered table-striped table ">
                            <tr>
                                <td class="border-2 border-black px-4 py-2">Номер заказа</td>
                                <td>{{ order.id }}</td>
                            </tr>
                            <tr>
                                <td class="border-2 border-black px-4 py-2">Клиент</td>
                                <td>{{ order.userName }}</td>
                            </tr>
                            <tr>
                                <td class="border-2 border-black px-4 py-2">Телефон клиента</td>
                                <td>{{ order.userPhone }}</td>
                            </tr>
                            <tr>
                                <td class="border-2 border-black px-4 py-2">Комментарий клиента</td>
                                <td>{{ order.userComment }}</td>
                            </tr>
                            {% if order.userId %}
                            <tr>
                                <td class="border-2 border-black px-4 py-2">ID клиента</td>
                                <td>{{ order.userId }}</td>
                            </tr>
                            {% endif %}
                            <tr>
                                <td class="border-2 border-black px-4 py-2">Статус заказа</td>
                                <td>{{ order.statusText }}</td>
                            </tr>
                            <tr>
                                <td class="border-2 border-black px-4 py-2">Дата заказа</td>
                                <td>{{ order.createdAt.format('d/m/Y - H:i:s') }}</td>
                            </tr>
                        </table>
                    </div>
                    <h5 class="text-xl font-sans mb-2">Товары в заказе</h5>
                    <div class="flex justify-center text-base font-sans">
                        <table class="border-2 border-black table-bordered table-striped table ">
                            <tr class="border-2 border-black">
                                <th class="border-2 border-black px-4 py-2">ID товара</th>
                                <th class="border-2 border-black px-4 py-2">Артикул товара</th>
                                <th class="border-2 border-black px-4 py-2">Название</th>
                                <th class="border-2 border-black px-4 py-2">Цена</th>
                                <th class="border-2 border-black px-4 py-2">Количество</th>
                            </tr>
                            {% for orderProduct in orderProducts %}
                                <tr>
                                    <td>{{ orderProduct.product.id }}</td>
                                    <td>{{ orderProduct.product.code }}</td>
                                    <td>{{ orderProduct.product.name }}</td>
                                    <td>${{ orderProduct.product.price }}</td>
                                    <td>{{ orderProduct.count }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}